version: '3.9'
services:
  backend:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: mysql_user
      MYSQL_PASSWORD: mysql_password
      MYSQL_ROOT_PASSWORD: mysql_root_password
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - .dbredis:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
